import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, dirname, resolve } from 'node:path'

const hash = (s: string) => createHash('sha256').update(s).digest('hex')

let generateCache: Record<string, string> = {}
let generateCachePath = ''

function getCacheDir() {
  let dir = process.cwd()
  while (dir !== '/') {
    const nm = resolve(dir, 'node_modules')
    if (existsSync(nm)) {
      const cacheDir = resolve(nm, '.on-zero')
      if (!existsSync(cacheDir)) {
        mkdirSync(cacheDir, { recursive: true })
      }
      return cacheDir
    }
    dir = resolve(dir, '..')
  }
  return null
}

function loadCache() {
  const cacheDir = getCacheDir()
  if (!cacheDir) return
  generateCachePath = resolve(cacheDir, 'generate-cache.json')
  try {
    generateCache = JSON.parse(readFileSync(generateCachePath, 'utf-8'))
  } catch {
    generateCache = {}
  }
}

function saveCache() {
  if (generateCachePath) {
    writeFileSync(generateCachePath, JSON.stringify(generateCache) + '\n', 'utf-8')
  }
}

function writeFileIfChanged(filePath: string, content: string): boolean {
  const contentHash = hash(content)
  const cachedHash = generateCache[filePath]

  if (cachedHash === contentHash && existsSync(filePath)) {
    return false
  }

  writeFileSync(filePath, content, 'utf-8')
  generateCache[filePath] = contentHash
  return true
}

function generateModelsFile(modelFiles: string[]) {
  const modelNames = modelFiles.map((f) => basename(f, '.ts')).sort()
  const getImportName = (name: string) => (name === 'user' ? 'userPublic' : name)

  const imports = modelNames
    .map((name) => `import * as ${getImportName(name)} from '../models/${name}'`)
    .join('\n')

  const sortedByImportName = [...modelNames].sort((a, b) =>
    getImportName(a).localeCompare(getImportName(b))
  )
  const modelsObj = `export const models = {\n${sortedByImportName.map((name) => `  ${getImportName(name)},`).join('\n')}\n}`

  return `// auto-generated by: on-zero generate\n${imports}\n\n${modelsObj}\n`
}

function generateTypesFile(modelFiles: string[]) {
  const modelNames = modelFiles.map((f) => basename(f, '.ts')).sort()
  const getSchemaName = (name: string) => (name === 'user' ? 'userPublic' : name)

  const typeExports = modelNames
    .map((name) => {
      const pascalName = name.charAt(0).toUpperCase() + name.slice(1)
      const schemaName = getSchemaName(name)
      return `export type ${pascalName} = TableInsertRow<typeof schema.${schemaName}>\nexport type ${pascalName}Update = TableUpdateRow<typeof schema.${schemaName}>`
    })
    .join('\n\n')

  return `import type { TableInsertRow, TableUpdateRow } from 'on-zero'\nimport type * as schema from './tables'\n\n${typeExports}\n`
}

function generateTablesFile(modelFiles: string[]) {
  const modelNames = modelFiles.map((f) => basename(f, '.ts')).sort()
  const getExportName = (name: string) => (name === 'user' ? 'userPublic' : name)

  const exports = modelNames
    .map((name) => `export { schema as ${getExportName(name)} } from '../models/${name}'`)
    .join('\n')

  return `// auto-generated by: on-zero generate\n// this is separate from models as otherwise you end up with circular types :/\n\n${exports}\n`
}

function generateReadmeFile() {
  return `# generated

this folder is auto-generated by on-zero. do not edit files here directly.

## what's generated

- \`models.ts\` - exports all models from ../models
- \`types.ts\` - typescript types derived from table schemas
- \`tables.ts\` - exports table schemas for type inference
- \`groupedQueries.ts\` - namespaced query re-exports for client setup
- \`syncedQueries.ts\` - namespaced syncedQuery wrappers for server setup
- \`syncedMutations.ts\` - valibot validators for mutation args (server auto-validation)

## usage guidelines

**do not import generated files outside of the data folder.**

### queries

write your queries as plain functions in \`../queries/\` and import them directly:

\`\`\`ts
// ✅ good - import from queries
import { channelMessages } from '~/data/queries/message'
\`\`\`

the generated query files are only used internally by zero client/server setup.

### types

you can import types from this folder, but prefer re-exporting from \`../types.ts\`:

\`\`\`ts
// ❌ okay but not preferred
import type { Message } from '~/data/generated/types'

// ✅ better - re-export from types.ts
import type { Message } from '~/data/types'
\`\`\`

## regeneration

files are regenerated when you run:

\`\`\`bash
bun on-zero generate
\`\`\`

or in watch mode:

\`\`\`bash
bun on-zero generate --watch
\`\`\`

## more info

see the [on-zero readme](./node_modules/on-zero/README.md) for full documentation.
`
}

function generateGroupedQueriesFile(
  queries: Array<{ name: string; sourceFile: string }>
) {
  const sortedFiles = [...new Set(queries.map((q) => q.sourceFile))].sort()

  const exports = sortedFiles
    .map((file) => `export * as ${file} from '../queries/${file}'`)
    .join('\n')

  return `/**
 * auto-generated by: on-zero generate
 *
 * grouped query re-exports for minification-safe query identity.
 * this file re-exports all query modules - while this breaks tree-shaking,
 * queries are typically small and few in number even in larger apps.
 */
${exports}
`
}

function generateSyncedQueriesFile(
  queries: Array<{
    name: string
    params: string
    valibotCode: string
    sourceFile: string
  }>
) {
  const queryByFile = new Map<string, typeof queries>()
  for (const q of queries) {
    if (!queryByFile.has(q.sourceFile)) {
      queryByFile.set(q.sourceFile, [])
    }
    queryByFile.get(q.sourceFile)!.push(q)
  }

  const sortedFiles = Array.from(queryByFile.keys()).sort()

  const imports = `// auto-generated by: on-zero generate
// server-side query definitions with validators
import { defineQuery, defineQueries } from '@rocicorp/zero'
import * as v from 'valibot'
import * as Queries from './groupedQueries'
`

  const namespaceDefs = sortedFiles
    .map((file) => {
      const fileQueries = queryByFile
        .get(file)!
        .sort((a, b) => a.name.localeCompare(b.name))

      const queryDefs = fileQueries
        .map((q) => {
          const validatorDef = q.valibotCode.trim()

          if (q.params === 'void' || !validatorDef) {
            return `  ${q.name}: defineQuery(() => Queries.${file}.${q.name}()),`
          }

          const indentedValidator = validatorDef
            .split('\n')
            .map((line, i) => (i === 0 ? line : `    ${line}`))
            .join('\n')

          return `  ${q.name}: defineQuery(
    ${indentedValidator},
    ({ args }) => Queries.${file}.${q.name}(args)
  ),`
        })
        .join('\n')

      return `const ${file} = {\n${queryDefs}\n}`
    })
    .join('\n\n')

  const queriesObject = sortedFiles.map((file) => `  ${file},`).join('\n')

  return `${imports}
${namespaceDefs}

export const queries = defineQueries({
${queriesObject}
})
`
}

// column type in schema → valibot validator
type SchemaColumn = {
  type: 'string' | 'number' | 'boolean' | 'json' | 'enum'
  optional: boolean
}

type ExtractedMutation = {
  name: string
  paramType: string // 'void' | inline type string | unresolved reference
  valibotCode: string // generated valibot code, or '' if skipped
}

// creates a TypeChecker that can resolve type references across files
function createTypeResolver(
  ts: typeof import('typescript'),
  files: Array<{ path: string; content: string }>,
  dir: string
) {
  // find tsconfig if it exists for path alias resolution
  const configPath = ts.findConfigFile(dir, ts.sys.fileExists, 'tsconfig.json')
  let compilerOptions: import('typescript').CompilerOptions = {
    target: ts.ScriptTarget.Latest,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    strict: false,
    skipLibCheck: true,
    noEmit: true,
  }

  if (configPath) {
    const configFile = ts.readConfigFile(configPath, ts.sys.readFile)
    if (configFile.config) {
      // use tsconfig's directory as base for path resolution (not the models dir)
      const parsed = ts.parseJsonConfigFileContent(
        configFile.config,
        ts.sys,
        dirname(configPath)
      )
      compilerOptions = { ...compilerOptions, ...parsed.options }
    }
  }

  // create a virtual file system host backed by real files + our content map
  const fileMap = new Map<string, string>()
  for (const f of files) {
    fileMap.set(f.path, f.content)
  }

  const host = ts.createCompilerHost(compilerOptions)
  const originalGetSourceFile = host.getSourceFile.bind(host)
  host.getSourceFile = (fileName, languageVersion, onError) => {
    const content = fileMap.get(fileName)
    if (content !== undefined) {
      return ts.createSourceFile(fileName, content, languageVersion, true)
    }
    return originalGetSourceFile(fileName, languageVersion, onError)
  }
  host.fileExists = (fileName) => fileMap.has(fileName) || ts.sys.fileExists(fileName)
  host.readFile = (fileName) => fileMap.get(fileName) ?? ts.sys.readFile(fileName)

  const program = ts.createProgram(
    files.map((f) => f.path),
    compilerOptions,
    host
  )
  const checker = program.getTypeChecker()

  return {
    program,
    checker,
    // resolve a type annotation node to a ts.Type
    resolveType(node: import('typescript').TypeNode): import('typescript').Type | null {
      try {
        return checker.getTypeFromTypeNode(node)
      } catch {
        return null
      }
    },
    // convert a resolved type to valibot code
    typeToValibot(type: import('typescript').Type): string {
      return tsTypeToValibot(ts, checker, type)
    },
  }
}

// find a specific exported arrow function's Nth parameter type in a checker-owned source file
function resolveParamType(
  ts: typeof import('typescript'),
  resolver: ReturnType<typeof createTypeResolver>,
  sourceFile: import('typescript').SourceFile,
  exportName: string,
  paramIndex: number
): import('typescript').Type | null {
  let result: import('typescript').Type | null = null

  ts.forEachChild(sourceFile, (node) => {
    if (result) return
    if (!ts.isVariableStatement(node)) return
    if (!node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) return

    const decl = node.declarationList.declarations[0]
    if (!decl || !ts.isVariableDeclaration(decl)) return
    if (decl.name.getText(sourceFile) !== exportName) return

    if (decl.initializer && ts.isArrowFunction(decl.initializer)) {
      const param = decl.initializer.parameters[paramIndex]
      if (param?.type) {
        result = resolver.resolveType(param.type)
      }
    }
  })

  return result
}

// find mutation handler param types in a resolver-owned source file
// walks `export const mutate = mutations(..., { handlerName: async (ctx, param: Type) => ... })`
function resolveMutationParamTypes(
  ts: typeof import('typescript'),
  resolver: ReturnType<typeof createTypeResolver>,
  sourceFile: import('typescript').SourceFile
): Map<string, import('typescript').Type> {
  const resolved = new Map<string, import('typescript').Type>()

  ts.forEachChild(sourceFile, (node) => {
    if (!ts.isVariableStatement(node)) return
    if (!node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) return

    const decl = node.declarationList.declarations[0]
    if (!decl || !ts.isVariableDeclaration(decl)) return
    if (decl.name.getText(sourceFile) !== 'mutate') return

    if (!decl.initializer || !ts.isCallExpression(decl.initializer)) return
    const args = decl.initializer.arguments

    // find the handlers object (last arg that is an object literal)
    let handlersArg: import('typescript').ObjectLiteralExpression | null = null
    for (let i = args.length - 1; i >= 0; i--) {
      if (ts.isObjectLiteralExpression(args[i]!)) {
        handlersArg = args[i] as import('typescript').ObjectLiteralExpression
        break
      }
    }
    if (!handlersArg) return

    for (const prop of handlersArg.properties) {
      if (!ts.isPropertyAssignment(prop) && !ts.isMethodDeclaration(prop)) continue
      const name = prop.name?.getText(sourceFile)
      if (!name) continue

      let params:
        | import('typescript').NodeArray<import('typescript').ParameterDeclaration>
        | null = null
      if (ts.isPropertyAssignment(prop)) {
        const init = prop.initializer
        if (ts.isArrowFunction(init) || ts.isFunctionExpression(init)) {
          params = init.parameters
        }
      } else if (ts.isMethodDeclaration(prop)) {
        params = prop.parameters
      }

      if (!params || params.length < 2) continue
      const typeNode = params[1]!.type
      if (!typeNode) continue

      const expanded = resolver.resolveType(typeNode)
      if (expanded) {
        resolved.set(name, expanded)
      }
    }
  })

  return resolved
}

type ModelMutations = {
  modelName: string
  hasCRUD: boolean
  columns: Record<string, SchemaColumn> // populated when hasCRUD
  primaryKeys: string[]
  custom: ExtractedMutation[]
}

function extractMutationsFromModel(
  ts: typeof import('typescript'),
  sourceFile: ReturnType<typeof ts.createSourceFile>,
  content: string,
  fileName: string,
  silent: boolean,
  typeToValibot: (typeString: string) => string | null,
  resolvedTypes?: Map<string, import('typescript').Type>,
  resolvedTypeToValibot?: (type: import('typescript').Type) => string
): ModelMutations | null {
  let mutateNode: import('typescript').CallExpression | null = null

  // find `export const mutate = mutations(...)`
  ts.forEachChild(sourceFile, (node) => {
    if (!ts.isVariableStatement(node)) return
    if (!node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) return
    const decl = node.declarationList.declarations[0]
    if (!decl || !ts.isVariableDeclaration(decl)) return
    if (decl.name.getText(sourceFile) !== 'mutate') return
    if (decl.initializer && ts.isCallExpression(decl.initializer)) {
      mutateNode = decl.initializer
    }
  })

  if (!mutateNode) {
    return {
      modelName: basename(fileName, '.ts'),
      hasCRUD: false,
      columns: {},
      primaryKeys: [],
      custom: [],
    }
  }

  const call = mutateNode as import('typescript').CallExpression
  const args = call.arguments

  // determine overload
  // 1-arg: mutations({ ... })
  // 2-arg: mutations(schema, perm)
  // 3-arg: mutations(schema, perm, { ... })
  const hasCRUD = args.length >= 2
  let handlersArg: import('typescript').ObjectLiteralExpression | null = null

  if (args.length === 1 && ts.isObjectLiteralExpression(args[0]!)) {
    handlersArg = args[0] as import('typescript').ObjectLiteralExpression
  } else if (args.length === 3 && ts.isObjectLiteralExpression(args[2]!)) {
    handlersArg = args[2] as import('typescript').ObjectLiteralExpression
  }

  // extract schema columns for CRUD generation
  const columns: Record<string, SchemaColumn> = {}
  const primaryKeys: string[] = []

  if (hasCRUD) {
    // parse schema columns from file content
    extractSchemaColumns(ts, sourceFile, columns, primaryKeys)
  }

  // extract custom mutation param types
  const custom: ExtractedMutation[] = []

  if (handlersArg) {
    for (const prop of handlersArg.properties) {
      if (!ts.isPropertyAssignment(prop) && !ts.isMethodDeclaration(prop)) continue

      const name = prop.name?.getText(sourceFile)
      if (!name) continue

      // find the arrow function or method
      let params:
        | import('typescript').NodeArray<import('typescript').ParameterDeclaration>
        | null = null

      if (ts.isPropertyAssignment(prop)) {
        const init = prop.initializer
        if (ts.isArrowFunction(init) || ts.isFunctionExpression(init)) {
          params = init.parameters
        }
      } else if (ts.isMethodDeclaration(prop)) {
        params = prop.parameters
      }

      if (!params) continue

      // second param is the mutation data (first is ctx)
      if (params.length < 2) {
        custom.push({ name, paramType: 'void', valibotCode: '' })
        continue
      }

      const secondParam = params[1]!
      const paramType = secondParam.type?.getText(sourceFile) || 'unknown'

      if (paramType === 'unknown') {
        custom.push({ name, paramType: 'unknown', valibotCode: '' })
        continue
      }

      let valibotCode = typeToValibot(paramType)

      // if direct parse failed (unresolved reference), use checker-resolved types
      if (!valibotCode && resolvedTypes && resolvedTypeToValibot) {
        const resolvedType = resolvedTypes.get(name)
        if (resolvedType) {
          valibotCode = resolvedTypeToValibot(resolvedType)
        }
      }

      custom.push({
        name,
        paramType,
        valibotCode: valibotCode || '',
      })
    }
  }

  return {
    modelName: '',
    hasCRUD,
    columns,
    primaryKeys,
    custom,
  }
}

function extractSchemaColumns(
  ts: typeof import('typescript'),
  sourceFile: ReturnType<typeof ts.createSourceFile>,
  columns: Record<string, SchemaColumn>,
  primaryKeys: string[]
) {
  // walk AST to find table(...).columns({...}).primaryKey(...)
  function visit(node: import('typescript').Node) {
    if (ts.isCallExpression(node)) {
      const text = node.expression.getText(sourceFile)

      // look for .primaryKey('id') or .primaryKey('id', 'otherId')
      if (text.endsWith('.primaryKey')) {
        for (const arg of node.arguments) {
          if (ts.isStringLiteral(arg)) {
            primaryKeys.push(arg.text)
          }
        }
      }

      // look for .columns({...})
      if (text.endsWith('.columns') && node.arguments.length === 1) {
        const obj = node.arguments[0]!
        if (ts.isObjectLiteralExpression(obj)) {
          for (const prop of obj.properties) {
            if (!ts.isPropertyAssignment(prop)) continue
            const colName = prop.name?.getText(sourceFile)
            if (!colName) continue

            const initText = prop.initializer.getText(sourceFile)
            const colType = parseColumnType(initText)
            columns[colName] = colType
          }
        }
      }
    }
    ts.forEachChild(node, visit)
  }
  visit(sourceFile)
}

function parseColumnType(initText: string): SchemaColumn {
  const optional = initText.includes('.optional()')
  let type: SchemaColumn['type'] = 'string'

  if (initText.startsWith('number(')) type = 'number'
  else if (initText.startsWith('boolean(')) type = 'boolean'
  else if (initText.startsWith('json(') || initText.startsWith('json<')) type = 'json'
  else if (initText.startsWith('enumeration(')) type = 'enum'

  return { type, optional }
}

function columnTypeToValibot(col: SchemaColumn): string {
  let base: string
  switch (col.type) {
    case 'string':
      base = 'v.string()'
      break
    case 'number':
      base = 'v.number()'
      break
    case 'boolean':
      base = 'v.boolean()'
      break
    case 'json':
      base = 'v.unknown()'
      break
    case 'enum':
      base = 'v.string()'
      break
    default:
      base = 'v.unknown()'
  }
  return col.optional ? `v.optional(v.nullable(${base}))` : base
}

function shouldSkipObjectKey(name: string): boolean {
  // TypeScript exposes symbol keys as synthetic names like "__@iterator@851".
  // These cannot come from JSON mutation payloads and break codegen if emitted.
  return name.startsWith('__@')
}

function formatObjectKey(name: string): string {
  return /^[$A-Z_a-z][$\w]*$/.test(name) ? name : JSON.stringify(name)
}

function schemaColumnsToValibot(
  columns: Record<string, SchemaColumn>,
  primaryKeys: string[],
  mode: 'insert' | 'update' | 'delete'
): string {
  const entries: string[] = []

  if (mode === 'delete') {
    // only PKs
    for (const pk of primaryKeys) {
      const col = columns[pk]
      if (col)
        entries.push(
          `${formatObjectKey(pk)}: ${columnTypeToValibot({ ...col, optional: false })}`
        )
    }
  } else if (mode === 'update') {
    // PKs required, rest optional
    for (const [name, col] of Object.entries(columns)) {
      const isPK = primaryKeys.includes(name)
      if (isPK) {
        entries.push(
          `${formatObjectKey(name)}: ${columnTypeToValibot({ ...col, optional: false })}`
        )
      } else {
        entries.push(
          `${formatObjectKey(name)}: ${columnTypeToValibot({ ...col, optional: true })}`
        )
      }
    }
  } else {
    // insert: all columns as-is
    for (const [name, col] of Object.entries(columns)) {
      entries.push(`${formatObjectKey(name)}: ${columnTypeToValibot(col)}`)
    }
  }

  return `v.object({\n    ${entries.join(',\n    ')},\n  })`
}

function generateSyncedMutationsFile(modelMutations: ModelMutations[]) {
  const sorted = [...modelMutations].sort((a, b) =>
    a.modelName.localeCompare(b.modelName)
  )

  const modelDefs = sorted
    .map((model) => {
      const entries: string[] = []

      // CRUD validators from schema
      if (model.hasCRUD && Object.keys(model.columns).length > 0) {
        for (const mode of ['insert', 'update', 'delete'] as const) {
          // skip if custom mutation overrides this CRUD op
          const hasCustomOverride = model.custom.some((m) => m.name === mode)
          if (hasCustomOverride) {
            // use the custom version's validator instead
            const customMut = model.custom.find((m) => m.name === mode)!
            if (customMut.valibotCode) {
              entries.push(
                `    ${mode}: ${extractValibotExpression(customMut.valibotCode)},`
              )
            } else {
              // fall back to schema-derived
              entries.push(
                `    ${mode}: ${schemaColumnsToValibot(model.columns, model.primaryKeys, mode)},`
              )
            }
          } else {
            entries.push(
              `    ${mode}: ${schemaColumnsToValibot(model.columns, model.primaryKeys, mode)},`
            )
          }
        }
      }

      // custom mutations (excluding CRUD overrides already handled)
      for (const mut of model.custom) {
        if (model.hasCRUD && ['insert', 'update', 'delete', 'upsert'].includes(mut.name))
          continue
        if (mut.paramType === 'void' || !mut.valibotCode) {
          entries.push(`    ${mut.name}: v.void_(),`)
          continue
        }
        entries.push(`    ${mut.name}: ${extractValibotExpression(mut.valibotCode)},`)
      }

      return `  ${model.modelName}: {\n${entries.join('\n')}\n  },`
    })
    .join('\n')

  return `// auto-generated by: on-zero generate
// mutation validators derived from model schemas and handler types
import * as v from 'valibot'

export const mutationValidators = {
${modelDefs}
}
`
}

// returns as-is since output is already a valibot expression
function extractValibotExpression(valibotCode: string): string {
  return valibotCode.trim() || 'v.unknown()'
}

// simple string-based type parser for inline type annotations from source text
// handles: primitives, inline objects { ... }, arrays, unions
// returns null for type references that need the TS checker
function parseTypeString(type: string): string | null {
  type = type.trim()

  // primitives
  if (type === 'string') return 'v.string()'
  if (type === 'number') return 'v.number()'
  if (type === 'boolean') return 'v.boolean()'
  if (type === 'void' || type === 'undefined') return 'v.void_()'
  if (type === 'null') return 'v.null_()'
  if (type === 'any' || type === 'unknown') return 'v.unknown()'

  // inline object: { key: type; ... }
  if (type.startsWith('{') && type.endsWith('}')) {
    const inner = type.slice(1, -1).trim()
    if (!inner) return 'v.object({})'
    // normalize newlines/commas to semicolons for splitting
    const normalized = inner.replace(/\n/g, '; ').replace(/;\s*;/g, ';')
    const entries: string[] = []
    for (const part of normalized.split(';')) {
      const trimmed = part.trim().replace(/,\s*$/, '')
      if (!trimmed) continue
      const match = trimmed.match(/^(?:readonly\s+)?(\w+)(\?)?:\s*(.+)$/)
      if (!match) continue
      const [, name, opt, typeStr] = match
      const parsed = parseTypeString(typeStr!.trim())
      if (!parsed) return null // can't resolve inner type
      let val = parsed
      if (opt) val = `v.optional(${val})`
      entries.push(`${formatObjectKey(name)}: ${val}`)
    }
    if (entries.length === 0) return 'v.object({})'
    return `v.object({\n    ${entries.join(',\n    ')},\n  })`
  }

  // array: T[]
  if (type.endsWith('[]')) {
    const inner = parseTypeString(type.slice(0, -2).trim())
    return inner ? `v.array(${inner})` : null
  }

  // unrecognized (type reference, complex generic, etc)
  return null
}

// convert a ts.Type to valibot code by walking the type checker AST
function tsTypeToValibot(
  ts: typeof import('typescript'),
  checker: import('typescript').TypeChecker,
  type: import('typescript').Type,
  seen?: Set<import('typescript').Type>
): string {
  // prevent infinite recursion on circular types
  // only track structured types (objects, intersections) — not primitives/unions
  if (!seen) seen = new Set()
  const flags = type.getFlags()
  if (flags & (ts.TypeFlags.Object | ts.TypeFlags.Intersection)) {
    if (seen.has(type)) return 'v.unknown()'
    seen.add(type)
  }

  const recurse = (t: import('typescript').Type) => tsTypeToValibot(ts, checker, t, seen)

  // primitives
  if (flags & ts.TypeFlags.String) return 'v.string()'
  if (flags & ts.TypeFlags.Number) return 'v.number()'
  if (flags & ts.TypeFlags.Boolean) return 'v.boolean()'
  if (flags & ts.TypeFlags.Void || flags & ts.TypeFlags.Undefined) return 'v.void_()'
  if (flags & ts.TypeFlags.Null) return 'v.null_()'
  if (flags & ts.TypeFlags.Any || flags & ts.TypeFlags.Unknown) return 'v.unknown()'
  if (flags & ts.TypeFlags.Never) return 'v.never()'

  // string/number/boolean literals
  if (flags & ts.TypeFlags.StringLiteral) {
    return `v.literal(${JSON.stringify((type as import('typescript').StringLiteralType).value)})`
  }
  if (flags & ts.TypeFlags.NumberLiteral) {
    return `v.literal(${(type as import('typescript').NumberLiteralType).value})`
  }
  if (flags & ts.TypeFlags.BooleanLiteral) {
    const name = (type as any).intrinsicName
    return `v.literal(${name === 'true'})`
  }

  // union
  if (type.isUnion()) {
    const members = type.types
    const hasNull = members.some((t) => t.getFlags() & ts.TypeFlags.Null)
    const hasUndefined = members.some(
      (t) => t.getFlags() & (ts.TypeFlags.Undefined | ts.TypeFlags.Void)
    )
    const rest = members.filter(
      (t) =>
        !(t.getFlags() & (ts.TypeFlags.Null | ts.TypeFlags.Undefined | ts.TypeFlags.Void))
    )
    if (
      rest.length === 2 &&
      rest.every((t) => t.getFlags() & ts.TypeFlags.BooleanLiteral)
    ) {
      let inner = 'v.boolean()'
      if (hasNull) inner = `v.nullable(${inner})`
      if (hasUndefined) inner = `v.optional(${inner})`
      return inner
    }

    if (rest.length === 0) return 'v.unknown()'

    let inner =
      rest.length === 1
        ? recurse(rest[0]!)
        : `v.union([${rest.map((t) => recurse(t)).join(', ')}])`

    if (hasNull) inner = `v.nullable(${inner})`
    if (hasUndefined) inner = `v.optional(${inner})`
    return inner
  }

  // resolve symbol property type with fallbacks
  const resolveSymbolType = (prop: import('typescript').Symbol) => {
    if (prop.valueDeclaration)
      return checker.getTypeOfSymbolAtLocation(prop, prop.valueDeclaration)
    if ((prop as any).declarations?.[0])
      return checker.getTypeOfSymbolAtLocation(prop, (prop as any).declarations[0])
    return checker.getDeclaredTypeOfSymbol(prop)
  }

  // intersection - use checker's merged properties directly
  if (type.isIntersection()) {
    const props = type.getProperties()
    if (props.length === 0) return 'v.object({})'
    const entries: string[] = []
    for (const prop of props) {
      const name = prop.getName()
      if (shouldSkipObjectKey(name)) continue
      const propType = resolveSymbolType(prop)
      const isOptional = !!(prop.getFlags() & ts.SymbolFlags.Optional)
      let val = recurse(propType)
      if (isOptional && !val.startsWith('v.optional(')) {
        val = `v.optional(${val})`
      }
      entries.push(`${formatObjectKey(name)}: ${val}`)
    }
    if (entries.length === 0) return 'v.object({})'
    return `v.object({\n    ${entries.join(',\n    ')},\n  })`
  }

  // object type with properties
  const props = type.getProperties()
  if (
    props.length > 0 &&
    (type.getFlags() & ts.TypeFlags.Object || (type as any).objectFlags)
  ) {
    const objectFlags = (type as import('typescript').ObjectType).objectFlags ?? 0

    // array
    if (objectFlags & ts.ObjectFlags.Reference) {
      const typeRef = type as import('typescript').TypeReference
      const symbol = type.getSymbol()
      const name = symbol?.getName()
      if (
        (name === 'Array' || name === 'ReadonlyArray') &&
        typeRef.typeArguments?.length === 1
      ) {
        return `v.array(${recurse(typeRef.typeArguments[0]!)})`
      }
    }

    // tuple
    if (objectFlags & ts.ObjectFlags.Tuple) {
      const typeRef = type as import('typescript').TypeReference
      const typeArgs = typeRef.typeArguments || []
      return `v.tuple([${typeArgs.map((t) => recurse(t)).join(', ')}])`
    }

    // regular object
    const entries: string[] = []
    for (const prop of props) {
      const name = prop.getName()
      if (shouldSkipObjectKey(name)) continue
      const propType = resolveSymbolType(prop)
      const isOptional = !!(prop.getFlags() & ts.SymbolFlags.Optional)
      let val = recurse(propType)
      if (isOptional && !val.startsWith('v.optional(')) {
        val = `v.optional(${val})`
      }
      entries.push(`${formatObjectKey(name)}: ${val}`)
    }
    if (entries.length === 0) return 'v.object({})'
    return `v.object({\n    ${entries.join(',\n    ')},\n  })`
  }

  // index signature / Record type
  const stringIndex = type.getStringIndexType()
  if (stringIndex) {
    return `v.record(v.string(), ${recurse(stringIndex)})`
  }
  const numberIndex = type.getNumberIndexType()
  if (numberIndex) {
    return `v.record(v.number(), ${recurse(numberIndex)})`
  }

  return 'v.unknown()'
}

export interface GenerateOptions {
  /** base data directory */
  dir: string
  /** run after generation */
  after?: string
  /** suppress output */
  silent?: boolean
}

export interface WatchOptions extends GenerateOptions {
  /** debounce delay in ms */
  debounce?: number
}

export interface GenerateResult {
  filesChanged: number
  modelCount: number
  schemaCount: number
  queryCount: number
  mutationCount: number
}

export async function generate(options: GenerateOptions): Promise<GenerateResult> {
  const { dir, after, silent } = options
  const baseDir = resolve(dir)
  const modelsDir = resolve(baseDir, 'models')
  const generatedDir = resolve(baseDir, 'generated')
  const queriesDir = resolve(baseDir, 'queries')

  if (!existsSync(generatedDir)) {
    mkdirSync(generatedDir, { recursive: true })
  }

  loadCache()

  const allModelFiles = readdirSync(modelsDir)
    .filter((f) => f.endsWith('.ts'))
    .sort()

  const filesWithSchema = allModelFiles.filter((f) =>
    readFileSync(resolve(modelsDir, f), 'utf-8').includes('export const schema = table(')
  )

  const writeResults = [
    writeFileIfChanged(
      resolve(generatedDir, 'models.ts'),
      generateModelsFile(allModelFiles)
    ),
    writeFileIfChanged(
      resolve(generatedDir, 'types.ts'),
      generateTypesFile(filesWithSchema)
    ),
    writeFileIfChanged(
      resolve(generatedDir, 'tables.ts'),
      generateTablesFile(filesWithSchema)
    ),
    writeFileIfChanged(resolve(generatedDir, 'README.md'), generateReadmeFile()),
  ]

  let filesChanged = writeResults.filter(Boolean).length
  let queryCount = 0
  let mutationCount = 0

  // lazy-load typescript
  const ts = await import('typescript')

  // lightweight string-based parser for inline type annotations from source text
  // handles simple cases: primitives, inline objects, arrays
  // returns null for type references that need the checker to resolve
  const typeToValibot = (paramType: string): string | null => {
    try {
      return parseTypeString(paramType.trim())
    } catch {
      return null
    }
  }

  // generate query files if queries directory exists
  if (existsSync(queriesDir)) {
    const queryFiles = readdirSync(queriesDir).filter((f) => f.endsWith('.ts'))

    const allQueries: Array<{
      name: string
      params: string
      valibotCode: string
      sourceFile: string
    }> = []

    // build resolver for query files (lazy - only created if needed)
    let queryResolver: ReturnType<typeof createTypeResolver> | null = null
    const getQueryResolver = () => {
      if (!queryResolver) {
        const allFiles = readdirSync(queriesDir)
          .filter((f) => f.endsWith('.ts'))
          .map((f) => ({
            path: resolve(queriesDir, f),
            content: readFileSync(resolve(queriesDir, f), 'utf-8'),
          }))
        queryResolver = createTypeResolver(ts, allFiles, queriesDir)
      }
      return queryResolver
    }

    for (const file of queryFiles) {
      const filePath = resolve(queriesDir, file)
      const fileBaseName = basename(file, '.ts')

      try {
        const content = readFileSync(filePath, 'utf-8')
        const sourceFile = ts.createSourceFile(
          filePath,
          content,
          ts.ScriptTarget.Latest,
          true
        )

        ts.forEachChild(sourceFile, (node) => {
          if (ts.isVariableStatement(node)) {
            const exportModifier = node.modifiers?.find(
              (m) => m.kind === ts.SyntaxKind.ExportKeyword
            )
            if (!exportModifier) return

            const declaration = node.declarationList.declarations[0]
            if (!declaration || !ts.isVariableDeclaration(declaration)) return

            const name = declaration.name.getText(sourceFile)
            if (name === 'permission') return

            if (declaration.initializer && ts.isArrowFunction(declaration.initializer)) {
              const params = declaration.initializer.parameters
              let paramType = 'void'

              if (params.length > 0) {
                const param = params[0]!
                paramType = param.type?.getText(sourceFile) || 'unknown'
              }

              let valibotCode = typeToValibot(paramType)

              // if direct parse failed (unresolved reference), use TypeChecker
              if (!valibotCode && params.length > 0 && params[0]!.type) {
                const resolver = getQueryResolver()
                const resolverSourceFile = resolver.program.getSourceFile(filePath)
                if (resolverSourceFile) {
                  const resolvedType = resolveParamType(
                    ts,
                    resolver,
                    resolverSourceFile,
                    name,
                    0
                  )
                  if (resolvedType) {
                    valibotCode = resolver.typeToValibot(resolvedType)
                  }
                }
              }

              if (valibotCode) {
                allQueries.push({
                  name,
                  params: paramType,
                  valibotCode,
                  sourceFile: fileBaseName,
                })
              } else if (!silent && paramType !== 'void') {
                console.error(`✗ ${name}: could not resolve type "${paramType}"`)
              }
            }
          }
        })
      } catch (err) {
        if (!silent) console.error(`Error processing ${file}:`, err)
      }
    }

    queryCount = allQueries.length

    const groupedChanged = writeFileIfChanged(
      resolve(generatedDir, 'groupedQueries.ts'),
      generateGroupedQueriesFile(allQueries)
    )
    const syncedChanged = writeFileIfChanged(
      resolve(generatedDir, 'syncedQueries.ts'),
      generateSyncedQueriesFile(allQueries)
    )

    if (groupedChanged) filesChanged++
    if (syncedChanged) filesChanged++
  }

  // generate mutation validators from model files
  const allModelMutations: ModelMutations[] = []

  // first pass: extract mutations, note which have unresolved types
  const mutationFiles: Array<{ path: string; content: string; baseName: string }> = []
  const unresolvedModels: Array<{ baseName: string; filePath: string }> = []

  for (const file of allModelFiles) {
    const filePath = resolve(modelsDir, file)
    const fileBaseName = basename(file, '.ts')

    try {
      const content = readFileSync(filePath, 'utf-8')

      mutationFiles.push({ path: filePath, content, baseName: fileBaseName })

      const sourceFile = ts.createSourceFile(
        filePath,
        content,
        ts.ScriptTarget.Latest,
        true
      )
      const result = extractMutationsFromModel(
        ts,
        sourceFile,
        content,
        filePath,
        !!silent,
        typeToValibot
      )

      if (result) {
        result.modelName = fileBaseName
        allModelMutations.push(result)

        // check if any custom mutations have unresolved types
        const hasUnresolved = result.custom.some(
          (m) => m.paramType !== 'void' && m.paramType !== 'unknown' && !m.valibotCode
        )
        if (hasUnresolved) {
          unresolvedModels.push({ baseName: fileBaseName, filePath })
        }
      }
    } catch (err) {
      if (!silent) console.error(`Error extracting mutations from ${file}:`, err)
    }
  }

  // second pass: resolve imported types using TypeChecker
  if (unresolvedModels.length > 0) {
    // build resolver with all ts files under baseDir for full import resolution
    // (model files may import types from generated files, shared types, etc)
    const collectTsFiles = (dir: string): Array<{ path: string; content: string }> => {
      const results: Array<{ path: string; content: string }> = []
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const fullPath = resolve(dir, entry.name)
        if (entry.isDirectory() && entry.name !== 'node_modules') {
          results.push(...collectTsFiles(fullPath))
        } else if (
          entry.isFile() &&
          entry.name.endsWith('.ts') &&
          !entry.name.endsWith('.d.ts')
        ) {
          results.push({ path: fullPath, content: readFileSync(fullPath, 'utf-8') })
        }
      }
      return results
    }
    const allFiles = collectTsFiles(baseDir)
    const modelResolver = createTypeResolver(ts, allFiles, baseDir)

    for (const { baseName, filePath } of unresolvedModels) {
      const resolverSourceFile = modelResolver.program.getSourceFile(filePath)
      if (!resolverSourceFile) continue

      const resolvedTypes = resolveMutationParamTypes(
        ts,
        modelResolver,
        resolverSourceFile
      )
      if (resolvedTypes.size === 0) continue

      // re-extract with resolved types
      const content = readFileSync(filePath, 'utf-8')
      const sourceFile = ts.createSourceFile(
        filePath,
        content,
        ts.ScriptTarget.Latest,
        true
      )
      const result = extractMutationsFromModel(
        ts,
        sourceFile,
        content,
        filePath,
        !!silent,
        typeToValibot,
        resolvedTypes,
        modelResolver.typeToValibot
      )

      if (result) {
        result.modelName = baseName
        // replace the old entry
        const idx = allModelMutations.findIndex((m) => m.modelName === baseName)
        if (idx >= 0) allModelMutations[idx] = result
      }
    }
  }

  // count total mutations (CRUD + custom)
  for (const model of allModelMutations) {
    if (model.hasCRUD) mutationCount += 3 // insert, update, delete
    mutationCount += model.custom.filter(
      (m) => !model.hasCRUD || !['insert', 'update', 'delete', 'upsert'].includes(m.name)
    ).length
  }

  if (allModelMutations.length > 0) {
    const mutationsChanged = writeFileIfChanged(
      resolve(generatedDir, 'syncedMutations.ts'),
      generateSyncedMutationsFile(allModelMutations)
    )
    if (mutationsChanged) filesChanged++
  }

  if (filesChanged > 0 && !silent) {
    console.info(
      `✓ ${allModelFiles.length} models (${filesWithSchema.length} schemas)${queryCount ? `, ${queryCount} queries` : ''}${mutationCount ? `, ${mutationCount} mutations` : ''}`
    )
  }

  // run after command
  if (filesChanged > 0 && after) {
    const { execSync } = await import('node:child_process')
    try {
      execSync(after, {
        stdio: 'inherit',
        env: { ...process.env, ON_ZERO_GENERATED_DIR: generatedDir },
      })
    } catch (err) {
      if (!silent) console.error(`Error running after command: ${err}`)
    }
  }

  saveCache()

  return {
    filesChanged,
    modelCount: allModelFiles.length,
    schemaCount: filesWithSchema.length,
    queryCount,
    mutationCount,
  }
}

export async function watch(options: WatchOptions) {
  const { dir, debounce = 1000 } = options
  const baseDir = resolve(dir)
  const modelsDir = resolve(baseDir, 'models')
  const queriesDir = resolve(baseDir, 'queries')
  const generatedDir = resolve(baseDir, 'generated')

  // initial run (silent)
  await generate({ ...options, silent: true })
  console.info('👀 watching...\n')

  const chokidar = await import('chokidar')

  let debounceTimer: ReturnType<typeof setTimeout> | null = null

  const debouncedRegenerate = (path: string, event: string) => {
    if (debounceTimer) clearTimeout(debounceTimer)
    console.info(`\n${event} ${path}`)
    debounceTimer = setTimeout(() => {
      generate({ ...options, silent: false })
    }, debounce)
  }

  const watcher = chokidar.watch([modelsDir, queriesDir], {
    persistent: true,
    ignoreInitial: true,
    ignored: [generatedDir],
  })

  watcher.on('change', (path) => debouncedRegenerate(path, '📝'))
  watcher.on('add', (path) => debouncedRegenerate(path, '➕'))
  watcher.on('unlink', (path) => debouncedRegenerate(path, '🗑️ '))

  return watcher
}
